--------------------------------------------------------
--  파일이 생성됨 - 수요일-11월-02-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table KURLY_HELP
--------------------------------------------------------

  CREATE TABLE "KULYDB"."KURLY_HELP" 
   (	"ADMINNAME" VARCHAR2(20 BYTE), 
	"BESTREVIEWDATE" DATE DEFAULT sysdate, 
	"GOODSIMAGE" VARCHAR2(20 BYTE), 
	"GOODSNAME" VARCHAR2(20 BYTE), 
	"BESTREVIEWTITLE" VARCHAR2(20 BYTE), 
	"BESTREVIEWCONTENTS" VARCHAR2(20 BYTE), 
	"BESTREVIEWNUM" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "KULYDB"."KURLY_HELP"."ADMINNAME" IS '회원이름';
   COMMENT ON COLUMN "KULYDB"."KURLY_HELP"."BESTREVIEWDATE" IS '리뷰작성일';
   COMMENT ON COLUMN "KULYDB"."KURLY_HELP"."GOODSIMAGE" IS '상품이미지';
   COMMENT ON COLUMN "KULYDB"."KURLY_HELP"."GOODSNAME" IS '상품이름';
   COMMENT ON COLUMN "KULYDB"."KURLY_HELP"."BESTREVIEWTITLE" IS '베스트리뷰제목

';
   COMMENT ON COLUMN "KULYDB"."KURLY_HELP"."BESTREVIEWCONTENTS" IS '베스트리뷰내용';
   COMMENT ON COLUMN "KULYDB"."KURLY_HELP"."BESTREVIEWNUM" IS '베스트리뷰글번호';
--------------------------------------------------------
--  DDL for Table KURLY_CART
--------------------------------------------------------

  CREATE TABLE "KULYDB"."KURLY_CART" 
   (	"GOODSIMAGE" VARCHAR2(20 BYTE), 
	"GOODSNAME" VARCHAR2(20 BYTE), 
	"GOODSPRICE" VARCHAR2(20 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"GOODSCODE" VARCHAR2(20 BYTE), 
	"GOODSSELECTNAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "KULYDB"."KURLY_CART"."GOODSIMAGE" IS '상품이미지';
   COMMENT ON COLUMN "KULYDB"."KURLY_CART"."GOODSNAME" IS '상품이름';
   COMMENT ON COLUMN "KULYDB"."KURLY_CART"."GOODSPRICE" IS '상품가격';
   COMMENT ON COLUMN "KULYDB"."KURLY_CART"."ID" IS '회원아이디';
   COMMENT ON COLUMN "KULYDB"."KURLY_CART"."GOODSCODE" IS '상품코드';
   COMMENT ON COLUMN "KULYDB"."KURLY_CART"."GOODSSELECTNAME" IS '선택한상품이름';
--------------------------------------------------------
--  DDL for Table KURLY_GOODS
--------------------------------------------------------

  CREATE TABLE "KULYDB"."KURLY_GOODS" 
   (	"GOODSCODE" VARCHAR2(20 BYTE), 
	"GOODSNAME" VARCHAR2(20 BYTE), 
	"GOODSINFO" VARCHAR2(20 BYTE), 
	"GOODSPRICE" VARCHAR2(20 BYTE), 
	"GOODSDISCOUNT" VARCHAR2(20 BYTE), 
	"GOODSDELIVERY" VARCHAR2(20 BYTE), 
	"GOODSPACKAGE" VARCHAR2(20 BYTE), 
	"GOODSUNIT" VARCHAR2(20 BYTE), 
	"GOODSWEIGHT" VARCHAR2(20 BYTE), 
	"GOODSORGIN" VARCHAR2(20 BYTE), 
	"GOODSSELECT" VARCHAR2(20 BYTE), 
	"GOODSCONTENTS1" VARCHAR2(20 BYTE), 
	"GOODSIMGAGE" VARCHAR2(20 BYTE), 
	"GOODSCONTENTS2" VARCHAR2(20 BYTE), 
	"GOODSSTOCK" NUMBER(10,0) DEFAULT 200
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "KULYDB"."KURLY_GOODS"."GOODSCODE" IS '상품코드';
   COMMENT ON COLUMN "KULYDB"."KURLY_GOODS"."GOODSNAME" IS '상품이름';
   COMMENT ON COLUMN "KULYDB"."KURLY_GOODS"."GOODSINFO" IS '상품상세?';
   COMMENT ON COLUMN "KULYDB"."KURLY_GOODS"."GOODSPRICE" IS '상품가격';
   COMMENT ON COLUMN "KULYDB"."KURLY_GOODS"."GOODSDISCOUNT" IS '상품할인';
   COMMENT ON COLUMN "KULYDB"."KURLY_GOODS"."GOODSDELIVERY" IS '배송방법';
   COMMENT ON COLUMN "KULYDB"."KURLY_GOODS"."GOODSPACKAGE" IS '포장타입';
   COMMENT ON COLUMN "KULYDB"."KURLY_GOODS"."GOODSUNIT" IS '판매단위';
   COMMENT ON COLUMN "KULYDB"."KURLY_GOODS"."GOODSWEIGHT" IS '상품무게';
   COMMENT ON COLUMN "KULYDB"."KURLY_GOODS"."GOODSORGIN" IS '상품 원산지
';
   COMMENT ON COLUMN "KULYDB"."KURLY_GOODS"."GOODSSELECT" IS '상품선택';
   COMMENT ON COLUMN "KULYDB"."KURLY_GOODS"."GOODSCONTENTS1" IS '상품상세1';
   COMMENT ON COLUMN "KULYDB"."KURLY_GOODS"."GOODSIMGAGE" IS '상품이미지';
   COMMENT ON COLUMN "KULYDB"."KURLY_GOODS"."GOODSCONTENTS2" IS '상품상세2';
   COMMENT ON COLUMN "KULYDB"."KURLY_GOODS"."GOODSSTOCK" IS '상품재고';
--------------------------------------------------------
--  DDL for Table KURLY_MEMBER
--------------------------------------------------------

  CREATE TABLE "KULYDB"."KURLY_MEMBER" 
   (	"ID" VARCHAR2(20 BYTE), 
	"PW" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"PHONE" NUMBER(15,0), 
	"ADDRESS" VARCHAR2(20 BYTE), 
	"GENDER" VARCHAR2(20 BYTE), 
	"BIRTH" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KURLY_GOODSLIST
--------------------------------------------------------

  CREATE TABLE "KULYDB"."KURLY_GOODSLIST" 
   (	"GOODSIMAGE" VARCHAR2(20 BYTE), 
	"GOODSPRICE" VARCHAR2(20 BYTE), 
	"GOODSRATE" VARCHAR2(20 BYTE), 
	"GOODSLISTCOUNT" NUMBER, 
	"GOODSINFO" VARCHAR2(20 BYTE), 
	"GOODSTITLE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KURLY_ORDER
--------------------------------------------------------

  CREATE TABLE "KULYDB"."KURLY_ORDER" 
   (	"GOODSIMAGE" VARCHAR2(20 BYTE), 
	"GOODSNAME" VARCHAR2(20 BYTE), 
	"GOODSPRICE" VARCHAR2(20 BYTE), 
	"ORDERNUM" VARCHAR2(20 BYTE), 
	"ORDERDATE" DATE DEFAULT sysdate, 
	"GOODSRATE" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"SHIPPINGRECIEVER" VARCHAR2(20 BYTE), 
	"OREDERPLACE" VARCHAR2(20 BYTE), 
	"ORDERGATEWAY" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"ORDERGOODSCOUNT" NUMBER DEFAULT 1, 
	"ORDERPHONE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KURLY_QNA
--------------------------------------------------------

  CREATE TABLE "KULYDB"."KURLY_QNA" 
   (	"GOODSIMAGE" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"QNATITLE" VARCHAR2(20 BYTE), 
	"QNACONTENTS" VARCHAR2(20 BYTE), 
	"QNADATE" VARCHAR2(20 BYTE) DEFAULT sysdate, 
	"QNALOCK" VARCHAR2(20 BYTE), 
	"QNAANSWER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KURLY_REVIEW
--------------------------------------------------------

  CREATE TABLE "KULYDB"."KURLY_REVIEW" 
   (	"GOODSNAME" VARCHAR2(20 BYTE), 
	"GOODSIMAGE" VARCHAR2(20 BYTE), 
	"REVIEWTITLE" VARCHAR2(20 BYTE), 
	"REVIEWCONTENTS" VARCHAR2(20 BYTE), 
	"GOODSSELECTNAME" VARCHAR2(20 BYTE), 
	"REVIEWIMAGE" VARCHAR2(20 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"REIVEWDATE" VARCHAR2(20 BYTE) DEFAULT sysdate
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KURLY_SHIPPING
--------------------------------------------------------

  CREATE TABLE "KULYDB"."KURLY_SHIPPING" 
   (	"SHIPPINGNAME" VARCHAR2(20 BYTE), 
	"SHIPPINGPHONE" VARCHAR2(20 BYTE), 
	"SHIPPINGADDRESS" VARCHAR2(20 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"SHIPPINGDEFAULTADDRESS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KURLY_WISH
--------------------------------------------------------

  CREATE TABLE "KULYDB"."KURLY_WISH" 
   (	"GOODSCODE" VARCHAR2(20 BYTE), 
	"GOODSNAME" VARCHAR2(20 BYTE), 
	"GOODSIMAGE" VARCHAR2(20 BYTE), 
	"GOODSPRICE" VARCHAR2(20 BYTE), 
	"GOODSRATE" VARCHAR2(20 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"WISHMAX" NUMBER DEFAULT 200
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KURLY_GOODS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KULYDB"."KURLY_GOODS_PK" ON "KULYDB"."KURLY_GOODS" ("GOODSCODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KURLY_MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KULYDB"."KURLY_MEMBER_PK" ON "KULYDB"."KURLY_MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table KURLY_GOODS
--------------------------------------------------------

  ALTER TABLE "KULYDB"."KURLY_GOODS" MODIFY ("GOODSDELIVERY" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_GOODS" MODIFY ("GOODSCODE" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_GOODS" MODIFY ("GOODSSTOCK" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_GOODS" MODIFY ("GOODSNAME" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_GOODS" MODIFY ("GOODSINFO" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_GOODS" MODIFY ("GOODSPRICE" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_GOODS" MODIFY ("GOODSDISCOUNT" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_GOODS" MODIFY ("GOODSPACKAGE" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_GOODS" MODIFY ("GOODSUNIT" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_GOODS" MODIFY ("GOODSWEIGHT" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_GOODS" MODIFY ("GOODSORGIN" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_GOODS" MODIFY ("GOODSSELECT" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_GOODS" MODIFY ("GOODSCONTENTS1" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_GOODS" MODIFY ("GOODSIMGAGE" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_GOODS" MODIFY ("GOODSCONTENTS2" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_GOODS" ADD CONSTRAINT "KURLY_GOODS_PK" PRIMARY KEY ("GOODSCODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KURLY_MEMBER
--------------------------------------------------------

  ALTER TABLE "KULYDB"."KURLY_MEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_MEMBER" ADD CONSTRAINT "KURLY_MEMBER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KULYDB"."KURLY_MEMBER" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_MEMBER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_MEMBER" MODIFY ("ADDRESS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KURLY_GOODSLIST
--------------------------------------------------------

  ALTER TABLE "KULYDB"."KURLY_GOODSLIST" MODIFY ("GOODSIMAGE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KURLY_ORDER
--------------------------------------------------------

  ALTER TABLE "KULYDB"."KURLY_ORDER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_ORDER" MODIFY ("SHIPPINGRECIEVER" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_ORDER" MODIFY ("OREDERPLACE" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_ORDER" MODIFY ("ORDERGOODSCOUNT" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_ORDER" MODIFY ("ORDERPHONE" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_ORDER" MODIFY ("GOODSIMAGE" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_ORDER" MODIFY ("GOODSNAME" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_ORDER" MODIFY ("GOODSPRICE" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_ORDER" MODIFY ("ORDERNUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KURLY_QNA
--------------------------------------------------------

  ALTER TABLE "KULYDB"."KURLY_QNA" MODIFY ("GOODSIMAGE" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_QNA" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_QNA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_QNA" MODIFY ("QNATITLE" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_QNA" MODIFY ("QNACONTENTS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KURLY_REVIEW
--------------------------------------------------------

  ALTER TABLE "KULYDB"."KURLY_REVIEW" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_REVIEW" MODIFY ("GOODSNAME" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_REVIEW" MODIFY ("GOODSIMAGE" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_REVIEW" MODIFY ("REVIEWTITLE" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_REVIEW" MODIFY ("REVIEWCONTENTS" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_REVIEW" MODIFY ("GOODSSELECTNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KURLY_SHIPPING
--------------------------------------------------------

  ALTER TABLE "KULYDB"."KURLY_SHIPPING" MODIFY ("SHIPPINGDEFAULTADDRESS" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_SHIPPING" MODIFY ("SHIPPINGADDRESS" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_SHIPPING" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KURLY_WISH
--------------------------------------------------------

  ALTER TABLE "KULYDB"."KURLY_WISH" MODIFY ("WISHMAX" NOT NULL ENABLE);
  ALTER TABLE "KULYDB"."KURLY_WISH" MODIFY ("ID" NOT NULL ENABLE);
